# All files in Project
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

# Gitlab commits
- repo: https://github.com/jorisroovers/gitlint
  rev:  v0.18.0
  hooks:
  - id: gitlint

# R
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.3.2
  hooks:
  - id: style-files
  - id: spell-check
  - id: no-browser-statement
  - id: no-debug-statement

# Python black
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black

# Python docformater
- repo: https://github.com/myint/docformatter
  rev: v1.5.1
  hooks:
  - id: docformatter
    args: [--in-place, --blank, --wrap-summaries=88, --wrap-descriptions=88]
